package com.example.demo.models;

/*
Creating this table using SQL for HSQLDB:
CREATE TABLE pets (
    pet_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    name VARCHAR(255) NOT NULL,
    owner VARCHAR(255) NOT NULL,
    PRIMARY KEY (pet_id)
)
*/
public record Pet(Integer pet_id, String name, String owner) {}
