package com.example.demo;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class DatabaseInitializer {
    public static void initialize() throws SQLException {
        DataSource db = DatabaseHelper.createDataSource();
        try (Connection conn = db.getConnection();
             PreparedStatement stmt = conn.prepareStatement(
                 "CREATE TABLE IF NOT EXISTS pets (" +
                     "pet_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), " +
                     "pet_name VARCHAR(255) NOT NULL, " +
                     "owner VARCHAR(255) NOT NULL, " +
                     "PRIMARY KEY (pet_id)" +
                     ")")) {
            stmt.execute();
        }
    }
}
