version: '3'
services:
  postgres_database:
    image: postgres:14-alpine
    container_name: sample_postgres_db
    restart: always
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/init.sql

    environment:
      POSTGRES_DB: 'db'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - "5432:5432"
  mysql_database:
    image: mysql
    container_name: sample_mysql_db
    restart: always
    volumes:
      - mysql_db_data:/var/lib/mysql
      - ./mysql_init.sql:/data/application/init.sql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
  mssql_database:
    build: ./mssql_database
    container_name: sample_mssql_db
    restart: always
    environment:
      SA_PASSWORD: 'Strong!Passw0rd'
      ACCEPT_EULA: 'Y'
    ports:
      - "1433:1433"
    volumes:
      - mssql_db_data:/var/opt/mssql
  mongo_database:
      image: mongo:latest
      container_name: sample_mongo_db_java
      restart: always
      environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
          MONGO_INITDB_DATABASE: my_database
      ports:
          - "27017:27017"
      volumes:
          - mongo_db_data:/data/db
volumes:
  postgres_db_data:
  mysql_db_data:
  mssql_db_data:
  mongo_db_data:
