version: '3'
services:
  postgres_database:
    image: postgres:14-alpine
    container_name: sample_postgres_db
    restart: always
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/init.sql

    environment:
      POSTGRES_DB: 'db'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - "5432:5432"

volumes:
  postgres_db_data:
