CREATE DATABASE IF NOT EXISTS db;
DROP TABLE IF EXISTS db.pets;
CREATE TABLE IF NOT EXISTS db.pets (
    pet_id INT AUTO_INCREMENT PRIMARY KEY,
    pet_name VARCHAR(250) NOT NULL,
    owner VARCHAR(250) NOT NULL
);