name: Run Spring Boot MySQL End-to-End Tests

on:
  pull_request:

jobs:
  spring_boot_mysql:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Import setup steps
        uses: ./.github/actions/setup

      - name: Start SpringBootMySQL (with and without Zen)
        working-directory: ./sample-apps/SpringBootMySQL
        run: |
          make run
          make runWithoutZen

      - name: Install Python dependencies
        run: python -m pip install -r end2end/requirements.txt

      - name: Run End-to-End tests
        working-directory: ./
        run: sleep 10 && python end2end/spring_boot_mysql.py
