name: Run End-to-End tests

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build with Gradle
        working-directory: ./
        run: |
          chmod +x gradlew
          make binaries
          make build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./dist/  # Adjust this path to your actual build output directory

  spring_boot_postgres:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      - name: Debug
        run: |
          ls -la
          cd dist && ls -la

      - name: Start mock server
        working-directory: ./end2end/server
        run: |
          docker build -t mock_core . 
          docker run --name mock_core -d -p 5000:5000 mock_core

      - name: Start SpringBootPostgres (with and without Zen)
        working-directory: ./sample-apps/SpringBootPostgres
        run: |
          make run
          make runWithoutZen

      - name: Install Python dependencies
        run: python -m pip install -r end2end/requirements.txt

      - name: Run End-to-End tests
        working-directory: ./
        run: python end2end/spring_boot_postgres.py
