name: Build and Run End-to-End Tests

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build with Gradle
        working-directory: ./
        run: |
          chmod +x gradlew
          make binaries
          make build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pkg-build
          path: ./

  spring_boot_postgres:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Start SpringBootPostgres (with and without Zen)
        working-directory: ./sample-apps/SpringBootPostgres
        run: |
          make run
          make runWithoutZen

      - name: Install Python dependencies
        run: python -m pip install -r end2end/requirements.txt

      - name: Run End-to-End tests
        working-directory: ./
        run: sleep 10 && python end2end/spring_boot_postgres.py

  spring_boot_mysql:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Start SpringBootMySQL (with and without Zen)
        working-directory: ./sample-apps/SpringBootMySQL
        run: |
          make run
          make runWithoutZen

      - name: Install Python dependencies
        run: python -m pip install -r end2end/requirements.txt

      - name: Run End-to-End tests
        working-directory: ./
        run: sleep 10 && python end2end/spring_boot_mysql.py