name: Run End-to-End tests

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build with Gradle
        working-directory: ./
        run: |
          chmod +x gradlew
          make binaries
          make build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pkg-build
          path: ./
  run_spring_boot_postgres:
    needs: build
    uses: ./.github/workflows/end2end/spring_boot_postgres.yml
  run_spring_boot_mysql:
    needs: build
    uses: ./.github/workflows/end2end/spring_boot_mysql.yml