name: Run Gradle Tests

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Add local.aikido.io to /etc/hosts
        run: |
          sudo echo "127.0.0.1 local.aikido.io" | sudo tee -a /etc/hosts
      - name: Download binaries & Build with Gradle
        working-directory: ./
        run: chmod +x gradlew && make binaries && make build
      - name: Start databases
        working-directory: ./sample-apps/databases
        run: docker compose up --build -d && sleep 10
      - name: Start mock server
        working-directory: ./end2end/server
        run: docker build -t mock_core . && docker run --name mock_core -d -p 5000:5000 mock_core
      - name: Create temporary directory
        run: |
          mkdir -p /opt/aikido
          chmod 777 /opt/aikido
      - name: Run test cases
        working-directory: ./
        run: chmod a+x gradlew && sudo make test

      - name: Run coverage with Gradle
        working-directory: ./
        run: chmod +x gradlew && ./gradlew clean && make cov
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: ./agent_api/build/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true